import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import { Suspense } from 'react';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  weight: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} antialiased overflow-hidden`}>
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
      </body>
    </html>
  );
}
